spring:
  profiles:
    active: local

  config:
    import:
      - classpath:/common/common.yml
      - classpath:/common/mail.yml
      - classpath:/common/swagger.yml
      - classpath:/common/paging.yml
      - classpath:env.properties
