spring:
  config:
    activate:
      on-profile: prod

  datasource:
  # TODO: 운영환경 데이터베이스 설정

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    kr.co.iabacus.sales: info

decorator:
  datasource:
    p6spy:
      enable-logging: false
