spring:
  profiles:
    active: local

  config:
    import:
      - classpath:/common/common.yml
      - classpath:/common/mail.yml
      - classpath:/common/auth.yml
      - optional:file:.env[.properties]
