spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/sales
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  session:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.security: trace
